### ISSUE TITLE
Elasticsearch 2.3.3 support

### ISSUE THREAD

**Issue by ttyS0** [jprante/elasticsearch-knapsack#104]
I think the Elastic people just wait until you update knapsack, and then deploy a new point release. :)

Please add support for the 2.3.3 release when you get a chance. 

Thanks!

**Comment by jprante** [comment]
I just pushed out knapsack plugin release 2.3.3.0 for Elasticsearch 2.3.3

**Comment by everkhoturov** [comment]
Ubuntu 14.04.4 LTS 64-bit

$ ./bin/plugin install http://xbib.org/repository/org/xbib/elasticsearch/plugin/elasticsearch-knapsack/2.3.3.0/elasticsearch-knapsack-2.3.3.0-plugin.zip
-> Installing from http://xbib.org/repository/org/xbib/elasticsearch/plugin/elasticsearch-knapsack/2.3.3.0/elasticsearch-knapsack-2.3.3.0-plugin.zip...
Trying http://xbib.org/repository/org/xbib/elasticsearch/plugin/elasticsearch-knapsack/2.3.3.0/elasticsearch-knapsack-2.3.3.0-plugin.zip ...
Downloading ..............................................................................................................................................................DONE
Verifying http://xbib.org/repository/org/xbib/elasticsearch/plugin/elasticsearch-knapsack/2.3.3.0/elasticsearch-knapsack-2.3.3.0-plugin.zip checksums if available ...
Downloading .DONE
ERROR: the version needs to contain major, minor and revision, and optionally the build: null

**Comment by jprante** [comment]
Thanks, The uploaded archive had a broken plugin-descriptor.properties file. I uploaded a fixed plugin zip under the same URL  http://xbib.org/repository/org/xbib/elasticsearch/plugin/elasticsearch-knapsack/2.3.3.0/elasticsearch-knapsack-2.3.3.0-plugin.zip
