### ISSUE TITLE
clarification on _pull call

### ISSUE THREAD

**Issue by forty4487** [jprante/elasticsearch-knapsack#70]
Sorry, but docs and details are a bit unclear.  

i have two separate clusters/instances on separate boxes.  I want to pull the index from one box to the other.  

source: 

host: host_a_ip
cluster: host_a_cluster_name
port: 9200

destination:

host: host_b_ip
cluster: host_b_cluster_name
port: 9200

1) Does the mapping have to be setup on the destination server before starting the _pull?

2) Is there any other port that needs to be opened on firewall to complete this action?

3) You don't have an example of _pull, so I just used your remote _push example, is this wrong?  Are there other parameters for _pull? 

curl -XPOST 'localhost:9200/test/_push?&cluster=remote&host=127.0.0.1&port=9201'

4) Does the plugin have to be installed on both instances to work or only the source of the curl request?

**Comment by jprante** [comment]
You can not use port 9200, it is port 9300 (internal ES protocol).

1. No

2. Maybe. I never tested with firewall settings. Port 9300 should be open - same condition as in any other ES cluster.

3. No, there are no other parameters.

4. Knapsack uses transport client and bulk indexing / scan/scroll. It is enough to install it on one node.
