### ISSUE TITLE
Import data only (no settings, no mappings)

### ISSUE THREAD

**Issue by arnaudbriche** [jprante/elasticsearch-knapsack#74]
Hi, 

It seems like it's currently not possible to only import the raw data, with no settings and mappings reapplied. 
What I'd like to do is to let knapsack import the raw data and have elasticsearch with auto index creation on and some templates to allow developpers to restore the data while applying their own modified mapping (with templates).

**Comment by jprante** [comment]
If you pass the parameter  `with_metadata=false` to knapsack import, it will not create indices or mappings. Default is `true`.

**Comment by arnaudbriche** [comment]
Works great. Thx
