### ISSUE TITLE
The exporting status still has this task after exporting finished.

### ISSUE THREAD

**Issue by dpcopper** [jprante/elasticsearch-knapsack#80]
Hi, I used knapsack to export an entire index. The size of index is 10G. 
I executed the command "curl -XPOST 'localhost:9200/logstash-2015-06-18/_export?path=/home3/elasticsearch/logstash-2015-06-18.zip'" to export.
Then I used command "curl -XPOST 'localhost:9200/_export/state'"  to check whether the export is finished. 
After a long time, I found the last modify time of the exported file isn't changing any more. But the exporting status still has a running task.  I don't know how to deal with it. 

My ES is  1.4.3, knapsack is 1.5.2.

**Comment by jprante** [comment]
Please use compatible versions. Knapsack 1.5.x.y is for ES 1.5

**Comment by dpcopper** [comment]
OK, I see. Thx!
