### ISSUE TITLE
filename is too long (>100 characters)

### ISSUE THREAD

**Issue by jmreymond** [jprante/elasticsearch-knapsack#83]
my export stops because the filename is too long

file name 'evol/mails/%21%7E%21UENERkVCMDkAAQACAAAAAAAAAAAAAAAAABgAAA
AAAAAA4ujoTBv1WUKt4ty4OdM4jMKAAAAQAAAAThSSMI1xBEanP5qvKo4CLQEAAAAA%40orange.fr/_source' is too long ( > 100 bytes)

If elasticsearch accept it, why elasticsearch-knapsack
 does not ?

**Comment by jprante** [comment]
Thanks for the report.

The issue is fixed in new releases:

2.0.0-beta2.1
1.7.2.0
1.6.2.0
1.5.2.1

**Comment by jmreymond** [comment]
thanks. It works great
