### ISSUE TITLE
exports faileds

### ISSUE THREAD

**Issue by ocuil** [jprante/elasticsearch-knapsack#85]
Hi there, first of all thanks for you plugins !!! I love it.

I try to do some exports but the elasticsarch process crash (now I know why) the question is, i have that:

[root@masternode ~]# curl -s -XPOST localhost:9200/_export/state?pretty
{
  "count" : 3,
  "states" : [ {
    "mode" : "export",
    "started" : "2015-09-28T12:15:30.222Z",
    "path" : "file:///opt/esdata/backups/ESBackups/logstash-2015.09.14.tar.gz",
    "node_name" : "Master 01"
  }, {
    "mode" : "export",
    "started" : "2015-09-28T12:23:52.822Z",
    "path" : "file:///opt/esdata/backups/ESBackups/logstash-2015.09.14.tar.gz",
    "node_name" : "Master 01"
  }, {
    "mode" : "export",
    "started" : "2015-09-28T12:28:46.637Z",
    "path" : "file:///opt/esdata/backups/ESBackups/logstash-2015.09.14.tar.gz",
    "node_name" : "Master 01"
  } ]
}

and when i try to delete that:

[root@masternode ~]# curl -XPOST 'localhost:9200/_export/abort?pretty'
{
  "aborted" : false
}

I cant reset to 0 that !!!  (thats exports dont finish because ES crash)

**Comment by jprante** [comment]
The `abort` command is for aborting running active export threads. If an export has failed, it may be that it can no longer be found to interrupt them. 

Clearing the entries is not possible in that case (patches are welcome!)

Because the state is transient in the cluster state, a cluster restart will drop them.

**Comment by ocuil** [comment]
I restart all cluster and that state stay there :-( and now if i try to do a new backup of a index ... the ES make backup of everything !!!

I remove the plugin from one master and after from other master with their reboots  ... try to install again but ... that state persist :-(

**Comment by jprante** [comment]
Which version do you use?

**Comment by ocuil** [comment]
1 versión, I restore the snap of vm ... now thats works well :-) thanks
