### ISSUE TITLE
ArchiveSession UTF-8 Encoding

### ISSUE THREAD

**Issue by masda70** [jprante/elasticsearch-knapsack#86]
ArchiveSession's write method should use "UTF-8" as the encoding for the payload's buffer:

`byte[] buf = packet.payload().getBytes("UTF-8");`

I don't know if there are any negative implications to this change.

However, I want to add for this reason and some others, knapsack (1.7.2) has caused more trouble than the time I thought it would save me for my particular reindexing need (not accounting for CPU time). I did not find an existing out-of-the-box (and efficient) alternative, so I ended up coding my own solution.

**Comment by jprante** [comment]
Thanks for the hint, much appreciated.

**Comment by jprante** [comment]
Fixed in 2.0.0-rc1.0, 1.7.2.1, 1.6.2.1, 1.5.2.2, 1.4.5.1, 1.3.4.1
